added jenkinsfile

diff --git a/jenkins/deploy.jenkinsfile b/jenkins/deploy.jenkinsfile
--- a/jenkins/deploy.jenkinsfile
+++ b/jenkins/deploy.jenkinsfile
@@ -73,23 +73,23 @@ pipeline {
             }
         }
 
-        stage('Rollback on Failure') {
-            steps {
-                script {
-                    echo "🔄 Checking for Rollback..."
+        // stage('Rollback on Failure') {
+        //     steps {
+        //         script {
+        //             echo "🔄 Checking for Rollback..."
 
-                    // ✅ Check container status
-                    sh """
-                    if [ \\$? -ne 0 ]; then
-                    echo " Deployment failed, rolling back..."
-                    docker tag \\${IMAGE_NAME}:\\${BACKUP_VERSION} \\${IMAGE_NAME}:latest
-                    docker-compose up -d
-                    fi
-                    """
+        //             // ✅ Check container status
+        //             sh """
+        //             if [ \\$? -ne 0 ]; then
+        //             echo " Deployment failed, rolling back..."
+        //             docker tag \\${IMAGE_NAME}:\\${BACKUP_VERSION} \\${IMAGE_NAME}:latest
+        //             docker-compose up -d
+        //             fi
+        //             """
 
-                }
-            }
-        }
+        //         }
+        //     }
+        // }
     }
 
     post {
